### ISSUE TITLE
[1.9] Crash on Forge 1835

### ISSUE THREAD

**Issue by ghost** [bdew-minecraft/generators#87]
Instance crash when trying to load using Forge 1835

http://pastebin.com/UY6F8Ar4

I know Forge is changing everyday, but also know they are minor fixes, hopefully we can get a new version soon.

**Comment by bdew** [comment]
Fixed in d3bf13824ebd67a22fd4c014ffd3ad86a1ffa1c1 + bdew/bdlib@f0905631d167e102a6a661d0ac070855451bf4f9.

Note that you will need to update BDLib and probably forge itself (there are more breaking changes after 1835, this build was with 1843)

**Comment by ghost** [comment]
Thanks, but updated to 1843 and still crashes. I guess either something is broke on my testing enviroment, or Forge keep breaking things by the second :P I guess at this point the best will be to wait for a stable/recommended version of forge. Or maybe I downloaded the wrong ones.

Here is the crash and the versions I used.
http://pastebin.com/paZUfGTa

**Comment by bdew** [comment]
I think you updated BDLib and Pressure Pipes but not Advanced Generators?

You want this build: http://minecraft.curseforge.com/projects/advanced-generators/files/2292327

**Comment by bdew** [comment]
>  I guess at this point the best will be to wait for a stable/recommended version of forge.

From what i understand there won't be one for 1.9.0, once they finish cleanup/refactoring they will update to 1.9.2.

**Comment by ghost** [comment]
Ohh ok ;) Well, I hope most devs keep up to date with the changes. Thanks a lot gonna be looking forward for those updates.
Yes that was the problem I guess I didnt saw the 0.9.20.5 one out there, that launch perfect.
